export type TransactionType = 'income' | 'expense'

export interface Transaction {
  id: string
  type: TransactionType
  amount: number
  category: string
  note: string
  date: string // ISO YYYY-MM-DD
  createdAt: number
  fromPlannedId?: string // if it was generated by validating a planned item
}

export interface Category {
  id: string
  label: string
  icon: string
  color: string
  type: TransactionType
}

// Échéances, dettes, dépenses/revenus prévisionnels
export type PlannedKind = 'debt' | 'scheduled' // dette ou échéance/prévision
export type PlannedDirection = 'out' | 'in' // sortant (à payer) ou entrant (à recevoir)
export type PlannedStatus = 'pending' | 'paid' | 'cancelled'

export interface Planned {
  id: string
  kind: PlannedKind
  direction: PlannedDirection
  title: string // "Loyer", "Dette à Marc"
  amount: number
  txCategory: string // catégorie utilisée pour la transaction générée
  dueDate: string // ISO YYYY-MM-DD
  status: PlannedStatus
  paidAt?: string // ISO when validated
  transactionId?: string // id of generated transaction
  note?: string
  createdAt: number
}
